-- Add the new one
INSERT [Profile.Module].[GenericRDF.Plugins] ([Name], [EnabledForPerson], [EnabledForGroup], [Label], [PropertyGroupURI], [CustomDisplayModule], [CustomEditModule], [CustomDisplayModuleXML], [CustomEditModuleXML]) VALUES (N'USCMentoring', 1, 0, N'Faculty Mentoring', N'http://profiles.catalyst.harvard.edu/ontology/prns#PropertyGroupFeaturedContent', N'USCMentoring', N'EditUSCMentoring', NULL, NULL)

EXEC [Profile.Module].[GenericRDF.AddUpdateOntology] @pluginName='USCMentoring'

-- fix the sort order, put it with Mentoring, make sure SortOrder matches the environment where you are doint this
SELECT *
  FROM [Ontology.].[PropertyGroupProperty] where PropertyURI like '%mentor%' or PropertyGroupURI = 'http://profiles.catalyst.harvard.edu/ontology/prns#PropertyGroupFeaturedContent' 
  order by SortOrder

UPDATE [Ontology.].[PropertyGroupProperty] set SortOrder = 50 where PropertyURI = 'http://profiles.catalyst.harvard.edu/ontology/plugins#USCMentoring'

-- remove old gadget from all people
-- remove filter
  -- First remove ORNG gadget from everybody. MAKE SURE ONLY USC FOLKS SHOW UP!!!
  DECLARE @PropertyNode INT
  SELECT @PropertyNode = _PropertyNode FROM [Ontology.].[ClassProperty] where Property = 'http://orng.info/ontology/orng#hasMentor'
  SELECT @PropertyNode
-- disable gadget

  -- run this and execute the output
  SELECT 'Exec [ORNG.].[RemoveAppFromAgent] @SubjectID=' + cast(Subject as varchar) + ', @AppID=102;' FROM [RDF.].Triple where Predicate = @PropertyNode 
	and Subject in (select NodeID from [UCSF.].vwPerson where InstitutionAbbreviation = 'USC');

-- remove the gadget but only for USC
 delete FROM [UCSF.ORNG].[InstitutionalizedApps] where AppID = 102 and InstitutionAbbreviation = 'USC';
 
 -- add one for Thomas Buchanan
DECLARE @NodeID BIGINT
SELECT @NodeID = nodeid FROM [UCSF.].vwPerson where InstitutionAbbreviation = 'USC' and LastName = 'Buchanan' and FirstName = 'Thomas';
SELECT @NodeID

EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name='USCMentoring', @NodeID=@nodeid, @Data='{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}', @SearchableData='USCMentoring Mentoring';


SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';'
FROM [UCSF.].[vwPerson] where PrettyURL like ('%thomas.buchanan') AND InstitutionAbbreviation = 'USC';

-- for EXCEL where column d is prettyurl
-- =CONCAT("SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''", "{""hasUSCMentoring"":""true"",""availableFor"":[],""contactPreferences"":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%", TEXTAFTER(d4, "/", -1), "') AND InstitutionAbbreviation = 'USC';")

-- SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%thomas.buchanan') AND InstitutionAbbreviation = 'USC';

-- from the EXCEL
-- 1) execute into text and copy to new query
-- 2) clean by removing (0 rows affected) and (1 rows affected), clean any that impact more than 2 rows
-- 3) run  
-- Works on all environments
 
 
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%thomas.buchanan') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%mariana.stern') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%david.conti') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%jeffrey.gold') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%leslie.clark') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%daryl.davies') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%michael.jakowec') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%wijbe.kast') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%ite.laird') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%cecilia.patinosutton') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%ping.wong') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%carolee.winstein') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%cheryl.craft') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%marvin.belzer') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%rebecca.lewthwaite') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%megan.herting') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%pin.wang') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%peggy.farnham') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%jing-hsiung.ou') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%weiming.yuan') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%sandrah.eckel') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%andre.ouellette') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%louis.dubeau') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%gage.crump') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%qilong.ying') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%derek.sieburth') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%ralf.langen') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%alicia.mcdonough') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%mark.frey') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%francesca.mariani') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%senta.georgianewell') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%keigo.machida') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%ansgar.siemer') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%john.mackay') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%yong-mi.kim') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%alan.epstein') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%lilyana.amezcua') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%pinghui.feng') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%david.hinton') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%stacey.niemiec') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%sophie.terp') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%stefanie.bodison') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%axel.schonthal') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%elizabeth.pyatak') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%gabriel.zada') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%anat.erdreich-epstein') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%mimi.kim') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%douglas.vanderbilt') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%johanna.olson') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%stefano.dasacco') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%hooman.djaladat') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%jeffrey.gold') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%benjamin.henwood') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%sue.ingles') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%michael.lieber') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%michael.neely') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%laura.perin') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%olga.solomon') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%min.yu') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%baruch.frenkel') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%beth.smith') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%woojin.an') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%amy.firth') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%andrew.mcmahon') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%shannon.mumenthaler') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%beth.smith') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%judd.rice') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%amir.goldkorn') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%michael.bonaguidi') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%jianming.xie') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%houda.alachkar') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%charleston.chiang') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%david.cobrinik') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%ram.subramanyan') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%zhipeng.lu') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%ahmad.besaratinia') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%amanda.tyree') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%amy.merrill-brugger') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%amy.lee') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%ann.yamada') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%kathleen.nelson') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%omid.akbari') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%rong.lu') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%shannon.mumenthaler') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%tobias.ulmer') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%philip.lumb') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%steven.siegel') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%lorraine.kelley-quon') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%ashaunta.anderson') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%sumeet.bhanvadia') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%nhu.tran') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%kimberly.gokoffski') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%isabel.lagomasino') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%marvin.belzer') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%stanley.louie') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%rohit.kohli') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%robinder.khemani') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%david.craig') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%amytis.towfighi') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%johanna.olson') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%tamara.simon') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%norah.terrault') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%brian.lee') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%suzanne.wenzel') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%shrikanth.narayanan') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%yong.cen') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%norah.terrault') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%suzanne.wenzel') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%brian.huang') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%juliet.emamaullee') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%anoopindar.ghuman') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%miller.huang') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%tishya.wren') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%maria.edman-woolcott') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%bradley.peterson') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%barbara.turner') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%hussein.yassine') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%gabriel.zada') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%beth.smith') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%michael.neely') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%tamara.simon') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%lorraine.kelley-quon') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%david.freyer') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%rohit.kohli') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%ching.lien') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%david.warburton') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%amy.west') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%michael.schumacher') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%ashaunta.anderson') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%claire.baldauf') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%liya.xu') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%stefano.dasacco') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%debra.lotstein') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%denise.sharon') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%cristina.roman') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%raina.pang') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%rex.moats') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%kay.jann') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%deepa.bhojwani') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%manal.tabbaa') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%erin.duffy') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%leah.duker') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%cynthia.munoz') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%elizabeth.burner') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%de-chen.lin') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%duke.han') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%catherine.argyriou') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%taylor.burkholder') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%anna.cushing') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%jeanine.hall') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%anna.kamitakahara') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%wendy.mack') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%astgik.petrosyan') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%jessica.shethbhutada') AND InstitutionAbbreviation = 'USC';
SELECT 'EXEC [Profile.Module].[GenericRDF.AddEditPluginData] @Name=''USCMentoring'', @NodeID=' + cast(nodeid as varchar) + ', @Data=''{"hasUSCMentoring":"true","availableFor":[],"contactPreferences":[]}'', @SearchableData=''USCMentoring Mentoring'';' FROM [UCSF.].[vwPerson] where PrettyURL like ('%jeanine.cho') AND InstitutionAbbreviation = 'USC';
